name: Unit and integration tests

on:
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x, 25.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Start Database
      run: docker compose -f docker-compose.dev.yaml up -d
      
    - name: Wait for Database to initialize
      run: sleep 10
      
    - name: Run Linter
      run: npm run lint
      
    - name: Run All Tests
      run: npm test